version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - /home/isunwoo/data/wordpress:/var/www/html
    env_file:
      - ./.env
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - /home/isunwoo/data/wordpress:/var/www/html
    env_file:
      - ./.env
    depends_on:
      - mariadb
    restart: on-failure

  mariadb:
    build: ./requirements/mariadb
    volumes:
      - /home/isunwoo/data/db:/var/lib/mysql/wordpress
    env_file:
      - ./.env
    restart: on-failure
