version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - WordPress:/var/www/html
    env_file:
      - ./.env
    restart: on-failure
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - WordPress:/var/www/html
    env_file:
      - ./.env
    depends_on:
      - mariadb
    restart: on-failure
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    volumes:
      - DB:/var/lib/mysql/wordpress
    env_file:
      - ./.env
    restart: on-failure
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  DB:
    driver: local
    driver_opts:
      type : none
      o : bind
      device : /home/isunwoo/data/db
  WordPress:
    driver: local
    driver_opts:
      type : none
      o : bind
      device : /home/isunwoo/data/wordpress
