version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - ./requirements/wordpress/wp:/wordpress
    env_file:
      - ./.env

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - ./requirements/wordpress/wp:/wordpress
    env_file:
      - ./.env

    depends_on:
      - mariadb

  mariadb:
    build: ./requirements/mariadb
    env_file:
      - ./.env
