version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 80:80
    depends_on:
      - wordpress

  wordpress:
    build: ./requirements/wordpress

  mariadb:
    build: ./requirements/mariadb
    ports:
      - 3306:3306
